use etl1;
select * from `healthcare`;

#1.	Retrieve the names of all patients in the database. 
select name  from  `healthcare`;

#2.	List the unique medical conditions present in the dataset.  
select medical_condition from `healthcare` where Medical_Condition = 'unique';

#3.	Find the total number of doctors in the healthcare system.  
select Doctor from `healthcare`;

#4.	Retrieve the details of all female patients.  
select * from `healthcare` where Gender = 'Female';

#5.	what is the average age of patients in the database. 
select  avg(Age) from `healthcare`;

#6.	Identify the patients who have more than one medical condition. 
select Medical_Condition from `healthcare` order by Medical_Condition asc limit 1;

#7.	List the names of all doctors.  
select Doctor from `healthcare`;

#8.Identify the most common medical condition among patients. 
select max(Medical_Condition) from `healthcare` ;

#9.Find the patients who are older than 60 years and have diabetes.  
select Age from `healthcare` where Age >60;

#10.Calculate the total revenue generated by the healthcare system.
select Billing_Amount from `healthcare`;

#11.Find the doctor with the oldest patient. 
select Doctor,Age from `healthcare` where Age>55;

#12.Calculate the average duration of medical visits. 
select avg(duration) from `healthcare`;

#13.Give the names of patients whose name starts with A.
select Name from  `healthcare` where Name like 'A%';

#14.How many male and female patients are there in dataset. 
select count(Gender) from `healthcare`;

#15.how many patients are normal. 
 select count(Test_Results) from `healthcare` where Test_Results ='normal';
 
 #16.how many patients are abnormal or Inconclusive.
 select count(Test_Results) from `healthcare` where Test_Results ='abnormal' or Test_Results = 'Inconclusive';

 # 17.how many patients of blood group AB+ are there of age above 52.  
 select * from `healthcare` where Blood_Type =' AB+ ' or Age>52;
 
 #18.	how many patients have paid the bill above 24890.  
 select count(Billing_Amount) from `healthcare` where Billing_Amount >24890;
 
 #19.	what are the names of patients having Asthma.  
 select Name , Medical_Condition  from `healthcare` where Medical_Condition = 'Asthma';
 
 #20.how many patients have cancer.  
 select count(Medical_Condition) from `healthcare` where Medical_Condition = 'cancer';

#21. what are the names and blood groups of patients admitted to room no. 292. 
select  Name,Blood_Type,Room_Number from `healthcare` where Room_Number = 292;

#22.how many males have Arthritis. 
 select count(Gender) from `healthcare` where Gender = 'male' or Medical_Condition = 'Arthritis';
 
 #23.How many patients were admitted to Harris and Sons hospital.  
 select count(Hospital) from  `healthcare` where Hospital = 'Harris and Sons';
 
 #24.what are the names of patients whose Insurance Provider are Cigna.  
 select Name,Insurance_Provider from `healthcare` where Insurance_Provider ='Cigna';
 
 #25.Name the Medical Condition having patients whose ages is greater than average age
 select Name,Medical_Condition,Age , avg(Age) `healthcare` where Age>avg(Age);
